name: Release

on:
  workflow_dispatch:
jobs:
  release:
    permissions:
      contents: write
      id-token: write

    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
      - uses: rubygems/release-gem@v1
